# Generated by Django 5.1.15 on 2026-09-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=64)),
                ('instance_date', models.DateTimeField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=128)),
                ('procedure', models.CharField(blank=True, max_length=256)),
                ('is_offplan', models.BooleanField(null=True)),
                ('is_freehold', models.BooleanField(null=True)),
                ('usage', models.CharField(blank=True, max_length=64)),
                ('area', models.CharField(blank=True, max_length=128)),
                ('property_type', models.CharField(blank=True, max_length=64)),
                ('property_subtype', models.CharField(blank=True, max_length=64)),
                ('transaction_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('procedure_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rooms', models.CharField(blank=True, max_length=32)),
                ('parking', models.CharField(blank=True, max_length=32)),
                ('nearest_metro', models.CharField(blank=True, max_length=128)),
                ('nearest_mall', models.CharField(blank=True, max_length=128)),
                ('nearest_landmark', models.CharField(blank=True, max_length=128)),
                ('total_buyer', models.PositiveIntegerField(blank=True, null=True)),
                ('total_seller', models.PositiveIntegerField(blank=True, null=True)),
                ('master_project', models.CharField(blank=True, max_length=256)),
                ('project', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['area'], name='ingestion_t_area_23b364_idx'), models.Index(fields=['property_type'], name='ingestion_t_propert_b0caf3_idx'), models.Index(fields=['instance_date'], name='ingestion_t_instanc_a9d445_idx')],
            },
        ),
    ]
