# Generated by Django 5.1.15 on 2026-09-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='parking',
            field=models.TextField(blank=True),
        ),
    ]
