# Generated by Django 5.1.15 on 2026-09-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_alter_transaction_parking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_hash', models.CharField(max_length=64, unique=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('area', models.CharField(blank=True, max_length=128)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('annual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('is_freehold', models.BooleanField(null=True)),
                ('actual_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property_type', models.CharField(blank=True, max_length=64)),
                ('property_subtype', models.CharField(blank=True, max_length=64)),
                ('rooms', models.CharField(blank=True, max_length=32)),
                ('usage', models.CharField(blank=True, max_length=64)),
                ('nearest_metro', models.CharField(blank=True, max_length=128)),
                ('nearest_mall', models.CharField(blank=True, max_length=128)),
                ('nearest_landmark', models.CharField(blank=True, max_length=128)),
                ('parking', models.TextField(blank=True)),
                ('total_properties', models.PositiveIntegerField(blank=True, null=True)),
                ('master_project', models.CharField(blank=True, max_length=256)),
                ('project', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['area'], name='ingestion_r_area_1df2e2_idx'), models.Index(fields=['property_type'], name='ingestion_r_propert_a96ec5_idx'), models.Index(fields=['registration_date'], name='ingestion_r_registr_56801f_idx')],
            },
        ),
    ]
